@rootUrl=http://localhost:8081
@authToken=xxx

POST {{rootUrl}}/inventory
accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "productId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "quantity": 1
}