@rootUrl=http://localhost:8080
@authToken=xxx

### Add Inventory

POST {{rootUrl}}/inventory
accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "productId": "05a02549-657b-4ad7-8459-1b6d20b668bb",
  "quantity": 600
}