@rootUrl=http://localhost:8081
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUZXN0VXNlciIsInVuaXF1ZV9uYW1lIjoiVGVzdFVzZXIiLCJyb2xlIjpbIndyaXRlIiwicmVhZCJdLCJleHAiOjE3NzA2Nzg0MjAsImlzcyI6IldhcmVob3VzZSIsImF1ZCI6IldhcmVob3VzZSJ9.F6vcdy3cgYnOJNmGAsvCLR9sl3XJ3FTOmAFOuFAJifc

GET {{rootUrl}}/products/945a9430-9803-425e-93b3-24f42315b245
accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

POST {{rootUrl}}/products
accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "test",
  "description": "test1",
  "price": 0.1
}
