@rootUrl=http://localhost:8080
@authToken=xxx

GET {{rootUrl}}/products/3fa85f64-5717-4562-b3fc-2c963f66afa6
accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}
