@rootUrl=http://localhost:8081
@authToken=xxx

### Get Product

GET {{rootUrl}}/products/945a9430-9803-425e-93b3-24f42315b245
accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Add Product

POST {{rootUrl}}/products
accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Gaming Laptop",
  "description": "High-performance gaming laptop with RTX 4080",
  "price": 1999.99
}

### Get All Products

GET {{rootUrl}}/products
accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}
